spring.application.name=trustbank

# Custom datasource config
app.datasource.main.driver-class-name=org.postgresql.Driver
app.datasource.main.jdbc-url=jdbc:postgresql://localhost:5432/first_city_bank
app.datasource.main.username=postgres
app.datasource.main.password=_K2Vq*SbuT/$t*w
app.datasource.main.pool-size=30

# Spring Boot standard datasource configuration (CRITICAL)
spring.datasource.url=jdbc:postgresql://localhost:5432/first_city_bank
spring.datasource.username=postgres
spring.datasource.password=_K2Vq*SbuT/$t*w
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.clean-disabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# API response
# Server Error Handling
server.error.include-message=always
server.error.include-binding-errors=always

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# App info to expose for Actuator
management.info.env.enabled=true
info.app.name=First City Bank And Trust
info.app.description=To foster economic prosperity, secure the financial future of the City's citizens, and facilitate commercial growth by providing a stable, trustworthy, and accessible financial institution.
info.app.version=1.1.0
info.app.author=Aleksandr Skopintsev
info.app.mentor=Garrett Master Thief

# Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
