plugins {
    id 'java'
}

allprojects {
    group = 'com.skopintsev'
    version = '1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}


subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17) // or your Java version
        }
    }

    dependencies {
        testImplementation platform('org.junit:junit-bom:5.10.0')
        testImplementation 'org.junit.jupiter:junit-jupiter'
    }

    test {
        useJUnitPlatform()
    }
}
