INSERT INTO sub_sectors
(sub_sector_code, sub_sector_name, description, sector_code)
VALUES
-- Energy sector
('ENER-FFU', 'Fossil Fuels',
 'Companies engaged in exploration, production, refining, and distribution of oil, natural gas, and coal. Highly capital intensive with significant geopolitical and environmental risks.',
 'ENER'),
('ENER-REN', 'Renewable Energy',
 'Companies developing and operating renewable energy sources including solar, wind, hydroelectric, geothermal, and biofuel power generation.',
 'ENER'),
('ENER-EST', 'Energy Storage',
 'Companies developing and manufacturing energy storage technologies including batteries, compressed air, and pumped hydro storage. Critical for grid stability and renewable energy integration.',
 'ENER'),
('ENER-TRA', 'Energy Transmission',
 'Companies operating energy transmission and distribution infrastructure including pipelines, electrical grids, and storage facilities. Characterized by regulated returns and stable cash flows.',
 'ENER'),

-- Materials sector
('MATR-CHE', 'Chemicals',
 'Companies producing industrial and specialty chemicals including basic chemicals, fertilizers, industrial gases, and specialty chemical products. Highly cyclical with significant exposure to energy costs.',
 'MATR'),
('MATR-CON', 'Construction Materials',
 'Companies manufacturing construction materials including cement, aggregates, glass, and building products. Performance closely tied to construction activity, infrastructure spending, and housing markets.',
 'MATR'),
('MATR-CPA', 'Containers & Packaging',
 'Companies producing packaging materials including paperboard, plastic, glass, and metal containers. Demand driven by consumer goods production and e-commerce growth.',
 'MATR'),
('MATR-MET', 'Metals & Mining',
 'Companies engaged in the extraction and processing of metals including base metals, precious metals, and industrial minerals. Includes mining operations, smelters, and processors.',
 'MATR'),
('MATR-PAP', 'Paper & Forest Products',
 'Companies producing paper products, packaging, and wood products from timber resources. Includes pulp & paper manufacturers and lumber producers.',
 'MATR'),

-- Industrials sector
('INDU-AER', 'Aerospace & Defense',
 'Companies manufacturing aircraft, defense systems, and related components. Includes commercial aerospace manufacturers, defense contractors, and space technology firms.',
 'INDU'),
('INDU-TRN', 'Transportation',
 'Companies providing transportation services and manufacturing transportation equipment. Includes airlines, trucking, railroads, and shipping companies.',
 'INDU'),
('INDU-ELE', 'Electrical Equipment',
 'Companies manufacturing electrical generation, transmission, distribution, and control equipment. Demand driven by industrial investment and infrastructure modernization.',
 'INDU'),
('INDU-ENG', 'Construction & Engineering',
 'Companies providing construction services and engineering expertise for infrastructure projects. Performance tied to public infrastructure spending and private construction activity.',
 'INDU'),
('INDU-LOG', 'Air Freight & Logistics',
 'Companies providing freight transportation, warehousing, and supply chain management services. Includes air freight carriers, logistics providers, and package delivery services.',
 'INDU'),

-- Consumer Discretionary sector
('COND-HHD', 'Household Durables',
 'Companies manufacturing long-lasting consumer goods including appliances, furniture, home furnishings, and consumer electronics. Purchase decisions influenced by housing activity, consumer confidence, and disposable income levels.',
 'COND'),
('COND-LEI', 'Leisure Products',
 'Companies producing recreational equipment including sporting goods, bicycles, musical instruments, and recreational vehicles.',
 'COND'),
('COND-TEX', 'Textiles, Apparel & Luxury Goods',
 'Companies manufacturing and retailing clothing, footwear, accessories, and luxury items. Highly competitive with rapid fashion cycles and significant margin pressure.',
 'COND'),
('COND-HOT', 'Hotels, Restaurants & Leisure',
 'Companies providing hospitality and entertainment services including hotels, restaurants, casinos, and leisure facilities. Performance highly sensitive to consumer spending patterns, travel trends, and economic conditions.',
 'COND'),
 ('COND-RET', 'Specialty Retail',
  'Companies operating specialized retail stores focusing on specific product categories. Includes retailers of electronics, home improvement, auto parts, and specialty foods.',
  'COND'),

-- Consumer Staples sector
('CONS-FDR', 'Food & Drug Retailing',
 'Companies operating grocery stores, supermarkets, and drug stores. Characterized by low margins, high volume, and intense competition. Benefiting from essential nature of products.',
 'CONS'),
('CONS-BEV', 'Beverages',
 'Companies producing non-alcoholic and alcoholic beverages including soft drinks, juices, beer, wine, and spirits. Characterized by strong brand loyalty and significant marketing expenditures.',
 'CONS'),
('CONS-FOO', 'Food Products',
 'Companies manufacturing processed food products including packaged foods, dairy products, meat products, and baked goods. Demand driven by population growth and changing consumption patterns.',
 'CONS'),
('CONS-TOB', 'Tobacco',
 'Companies manufacturing tobacco products including cigarettes, cigars, and smokeless tobacco. Facing declining volumes in developed markets but benefiting from pricing power and addiction characteristics.',
 'CONS'),
('CONS-HHP', 'Household Products',
 'Companies manufacturing non-durable household goods including cleaning products, paper products, and other consumables. Characterized by stable demand and brand loyalty.',
 'CONS'),
('CONS-PER', 'Personal Products',
 'Companies manufacturing personal care and beauty products including cosmetics, skincare, hair care, and fragrances.',
 'CONS'),

-- Healthcare sector
('HLTH-EQP', 'Health Care Equipment',
 'Companies manufacturing medical devices, equipment, and supplies used in healthcare delivery. Includes producers of diagnostic equipment, surgical instruments, and medical implants. Characterized by high R&D investment and regulatory approvals.',
 'HLTH'),
('HLTH-BIO', 'Biotechnology',
 'Companies researching and developing biological-based therapies and diagnostic tools. Includes firms developing novel drugs, gene therapies, and biological research tools. Characterized by high risk, high reward profiles with lengthy development timelines.',
 'HLTH'),
('HLTH-PHA', 'Pharmaceuticals',
 'Companies researching, developing, and manufacturing prescription and over-the-counter drugs. Facing patent expirations, pricing pressures, and regulatory scrutiny.',
 'HLTH'),
('HLTH-LST', 'Life Sciences Tools & Services',
 'Companies providing tools, technologies, and services to support life sciences research and healthcare delivery. Includes providers of laboratory equipment, clinical research services, and diagnostic testing. Benefiting from increasing R&D investment.',
 'HLTH'),

-- Financials sector
('FINL-BNK', 'Banks',
 'Depository institutions accepting deposits and making loans. Includes commercial banks, savings institutions, and credit unions. Performance driven by net interest margins, credit quality, and regulatory capital requirements.',
 'FINL'),
('FINL-CFN', 'Consumer Finance',
 'Companies providing credit to consumers outside the traditional banking system. Includes credit card issuers, personal loan providers, and auto finance companies. Sensitive to consumer credit conditions and interest rate environments.',
 'FINL'),
('FINL-CAP', 'Capital Markets',
 'Companies facilitating capital formation and investment activities. Includes investment banks, securities exchanges, and asset managers. Performance linked to capital market activity, trading volumes, and asset management flows.',
 'FINL'),
('FINL-INS', 'Insurance',
 'Companies providing risk transfer through insurance products. Includes life, health, property & casualty insurers, and reinsurance companies. Performance influenced by underwriting discipline, investment returns, and catastrophic events.',
 'FINL'),
 ('FINL-REI', 'Real Estate Investment Trusts',
  'Companies owning and operating income-producing real estate structured as REITs. Includes equity REITs, mortgage REITs, and hybrid REITs. Required to distribute most taxable income to shareholders, providing yield characteristics.',
  'FINL'),

-- Utilities sector
('UTIL-ELE', 'Electric Utilities',
 'Companies generating, transmitting, and distributing electricity. Includes regulated utilities, independent power producers, and renewable energy generators. Characterized by stable demand, regulated returns, and infrastructure investment requirements.',
 'UTIL'),
('UTIL-GAS', 'Gas Utilities',
 'Companies distributing natural gas to residential, commercial, and industrial customers. Performance influenced by regulatory frameworks and energy transition policies.',
 'UTIL'),
('UTIL-WAT', 'Water Utilities',
 'Companies providing water collection, treatment, and distribution services. Includes regulated water utilities and water treatment companies. Essential service with stable demand and significant infrastructure reinvestment needs.',
 'UTIL'),
('UTIL-MUL', 'Multi-Utilities',
 'Companies operating across multiple utility service categories. Includes diversified utilities providing electricity, natural gas, and water services. Benefits from business diversification while maintaining regulated return characteristics.',
 'UTIL'),

-- Real Estate sector
('REAL-RET', 'Retail REITs',
 'REITs owning and operating retail properties including shopping centers, malls, and outlet centers. Performance driven by retail sales, tenant quality, and location characteristics.',
 'REAL'),
('REAL-RES', 'Residential REITs',
 'REITs owning and operating residential properties including apartments, single-family rentals, and student housing. Performance influenced by demographic trends, household formation, and rental affordability.',
 'REAL'),
('REAL-OFF', 'Office REITs',
 'REITs owning and operating office buildings and business parks. Performance tied to employment growth, corporate expansion, and office space utilization trends.',
 'REAL'),
('REAL-IND', 'Industrial REITs',
 'REITs owning and operating industrial properties including warehouses, distribution centers, and manufacturing facilities. Benefiting from e-commerce growth and supply chain restructuring.',
 'REAL'),
('REAL-SPE', 'Specialized REITs',
 'REITs owning specialized property types including healthcare facilities, data centers, self-storage, and timberlands. Each segment has unique demand drivers and growth characteristics.',
 'REAL');
